### PR TITLE
little more adjustments

### PR DESCRIPTION
**Pull request by BaderEddineOuaich**
Looks like [forground_color](https://github.com/gammasoft71/xtd/blob/master/src/xtd.core/src/xtd/internal/__opaque_console_gcc.cpp#L668) and [background_color](https://github.com/gammasoft71/xtd/blob/master/src/xtd.core/src/xtd/internal/__opaque_console_gcc.cpp#L557) functions in [__opaque_console_gcc.cpp](https://github.com/gammasoft71/xtd/blob/master/src/xtd.core/src/xtd/internal/__opaque_console_gcc.cpp) intent to have the same logic as their relatives in [console.cpp](https://github.com/BaderEddineOuaich/xtd/blob/15e213070ef05996a54ef9b0abecab1ef2afd736/src/xtd.core.native.unix/src/xtd/native/unix/console.cpp#L546) ? if so its reordered.
Have a nice day!

### CODE REVIEW

**Comment by gammasoft71** [comment]
Yes your right but you forgot the return value "false"... I add it  ;-)

**Comment by BaderEddineOuaich** [comment]
Oh yes you're right, i forget the return value! thanks for adding that :) 👍

**Comment by gammasoft71** [comment]
Just for your information, the files internal/__opaque_console_gcc.cpp and internal/__opaque_console_win32.cpp are going to disappear in favor of the implementation in the xtd.core.native.unix and xtd.core.native.win32 libraries as soon as I fix a callback problem on the unix signals

Have a nice day too.

**Comment by BaderEddineOuaich** [comment]
Roger that, thanks for letting me know.
Have a nice day!

**Pull request closed without merging**
